// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AdvInfoFieldRef.proto

package com.example.brokerterminal.proto;

public final class AdvInfoFieldRefProto {
  private AdvInfoFieldRefProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_brokerterminal_proto_AdvInfoFieldRef_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_brokerterminal_proto_AdvInfoFieldRef_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025AdvInfoFieldRef.proto\022 com.example.bro" +
      "kerterminal.proto\032\022MessageEnums.proto\"\200\001" +
      "\n\017AdvInfoFieldRef\022\r\n\005alias\030\001 \001(\t\022\024\n\007capt" +
      "ion\030\002 \001(\tH\000\210\001\001\022<\n\010dataType\030\003 \001(\0162*.com.e" +
      "xample.brokerterminal.proto.DataTypeB\n\n\010" +
      "_captionB\032B\024AdvInfoFieldRefProtoH\001P\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.example.brokerterminal.proto.MessageEnumsProto.getDescriptor(),
        });
    internal_static_com_example_brokerterminal_proto_AdvInfoFieldRef_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_brokerterminal_proto_AdvInfoFieldRef_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_brokerterminal_proto_AdvInfoFieldRef_descriptor,
        new java.lang.String[] { "Alias", "Caption", "DataType", "Caption", });
    com.example.brokerterminal.proto.MessageEnumsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
