// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataFieldValue.proto

package com.example.brokerterminal.proto;

/**
 * Protobuf type {@code com.example.brokerterminal.proto.DataFieldValue}
 */
public final class DataFieldValue extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.brokerterminal.proto.DataFieldValue)
    DataFieldValueOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DataFieldValue.newBuilder() to construct.
  private DataFieldValue(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DataFieldValue() {
    alias_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DataFieldValue();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.brokerterminal.proto.DataFieldValueProto.internal_static_com_example_brokerterminal_proto_DataFieldValue_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.brokerterminal.proto.DataFieldValueProto.internal_static_com_example_brokerterminal_proto_DataFieldValue_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.brokerterminal.proto.DataFieldValue.class, com.example.brokerterminal.proto.DataFieldValue.Builder.class);
  }

  public static final int ALIAS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object alias_ = "";
  /**
   * <pre>
   * Идентификатор поля для которого устанавливается значение
   * </pre>
   *
   * <code>string alias = 1;</code>
   * @return The alias.
   */
  @java.lang.Override
  public java.lang.String getAlias() {
    java.lang.Object ref = alias_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      alias_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Идентификатор поля для которого устанавливается значение
   * </pre>
   *
   * <code>string alias = 1;</code>
   * @return The bytes for alias.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAliasBytes() {
    java.lang.Object ref = alias_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      alias_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VALUE_FIELD_NUMBER = 2;
  private com.example.brokerterminal.proto.ValueRef value_;
  /**
   * <pre>
   * Описание значения поля
   * </pre>
   *
   * <code>.com.example.brokerterminal.proto.ValueRef value = 2;</code>
   * @return Whether the value field is set.
   */
  @java.lang.Override
  public boolean hasValue() {
    return value_ != null;
  }
  /**
   * <pre>
   * Описание значения поля
   * </pre>
   *
   * <code>.com.example.brokerterminal.proto.ValueRef value = 2;</code>
   * @return The value.
   */
  @java.lang.Override
  public com.example.brokerterminal.proto.ValueRef getValue() {
    return value_ == null ? com.example.brokerterminal.proto.ValueRef.getDefaultInstance() : value_;
  }
  /**
   * <pre>
   * Описание значения поля
   * </pre>
   *
   * <code>.com.example.brokerterminal.proto.ValueRef value = 2;</code>
   */
  @java.lang.Override
  public com.example.brokerterminal.proto.ValueRefOrBuilder getValueOrBuilder() {
    return value_ == null ? com.example.brokerterminal.proto.ValueRef.getDefaultInstance() : value_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(alias_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, alias_);
    }
    if (value_ != null) {
      output.writeMessage(2, getValue());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(alias_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, alias_);
    }
    if (value_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getValue());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.brokerterminal.proto.DataFieldValue)) {
      return super.equals(obj);
    }
    com.example.brokerterminal.proto.DataFieldValue other = (com.example.brokerterminal.proto.DataFieldValue) obj;

    if (!getAlias()
        .equals(other.getAlias())) return false;
    if (hasValue() != other.hasValue()) return false;
    if (hasValue()) {
      if (!getValue()
          .equals(other.getValue())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ALIAS_FIELD_NUMBER;
    hash = (53 * hash) + getAlias().hashCode();
    if (hasValue()) {
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.brokerterminal.proto.DataFieldValue parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.brokerterminal.proto.DataFieldValue parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.brokerterminal.proto.DataFieldValue parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.brokerterminal.proto.DataFieldValue parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.brokerterminal.proto.DataFieldValue parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.brokerterminal.proto.DataFieldValue parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.brokerterminal.proto.DataFieldValue parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.brokerterminal.proto.DataFieldValue parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.brokerterminal.proto.DataFieldValue parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.brokerterminal.proto.DataFieldValue parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.brokerterminal.proto.DataFieldValue parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.brokerterminal.proto.DataFieldValue parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.brokerterminal.proto.DataFieldValue prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.brokerterminal.proto.DataFieldValue}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.brokerterminal.proto.DataFieldValue)
      com.example.brokerterminal.proto.DataFieldValueOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.brokerterminal.proto.DataFieldValueProto.internal_static_com_example_brokerterminal_proto_DataFieldValue_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.brokerterminal.proto.DataFieldValueProto.internal_static_com_example_brokerterminal_proto_DataFieldValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.brokerterminal.proto.DataFieldValue.class, com.example.brokerterminal.proto.DataFieldValue.Builder.class);
    }

    // Construct using com.example.brokerterminal.proto.DataFieldValue.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      alias_ = "";
      value_ = null;
      if (valueBuilder_ != null) {
        valueBuilder_.dispose();
        valueBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.brokerterminal.proto.DataFieldValueProto.internal_static_com_example_brokerterminal_proto_DataFieldValue_descriptor;
    }

    @java.lang.Override
    public com.example.brokerterminal.proto.DataFieldValue getDefaultInstanceForType() {
      return com.example.brokerterminal.proto.DataFieldValue.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.brokerterminal.proto.DataFieldValue build() {
      com.example.brokerterminal.proto.DataFieldValue result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.brokerterminal.proto.DataFieldValue buildPartial() {
      com.example.brokerterminal.proto.DataFieldValue result = new com.example.brokerterminal.proto.DataFieldValue(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.example.brokerterminal.proto.DataFieldValue result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.alias_ = alias_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.value_ = valueBuilder_ == null
            ? value_
            : valueBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.brokerterminal.proto.DataFieldValue) {
        return mergeFrom((com.example.brokerterminal.proto.DataFieldValue)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.brokerterminal.proto.DataFieldValue other) {
      if (other == com.example.brokerterminal.proto.DataFieldValue.getDefaultInstance()) return this;
      if (!other.getAlias().isEmpty()) {
        alias_ = other.alias_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasValue()) {
        mergeValue(other.getValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              alias_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getValueFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object alias_ = "";
    /**
     * <pre>
     * Идентификатор поля для которого устанавливается значение
     * </pre>
     *
     * <code>string alias = 1;</code>
     * @return The alias.
     */
    public java.lang.String getAlias() {
      java.lang.Object ref = alias_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        alias_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Идентификатор поля для которого устанавливается значение
     * </pre>
     *
     * <code>string alias = 1;</code>
     * @return The bytes for alias.
     */
    public com.google.protobuf.ByteString
        getAliasBytes() {
      java.lang.Object ref = alias_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        alias_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Идентификатор поля для которого устанавливается значение
     * </pre>
     *
     * <code>string alias = 1;</code>
     * @param value The alias to set.
     * @return This builder for chaining.
     */
    public Builder setAlias(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      alias_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Идентификатор поля для которого устанавливается значение
     * </pre>
     *
     * <code>string alias = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAlias() {
      alias_ = getDefaultInstance().getAlias();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Идентификатор поля для которого устанавливается значение
     * </pre>
     *
     * <code>string alias = 1;</code>
     * @param value The bytes for alias to set.
     * @return This builder for chaining.
     */
    public Builder setAliasBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      alias_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.example.brokerterminal.proto.ValueRef value_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.brokerterminal.proto.ValueRef, com.example.brokerterminal.proto.ValueRef.Builder, com.example.brokerterminal.proto.ValueRefOrBuilder> valueBuilder_;
    /**
     * <pre>
     * Описание значения поля
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.ValueRef value = 2;</code>
     * @return Whether the value field is set.
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Описание значения поля
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.ValueRef value = 2;</code>
     * @return The value.
     */
    public com.example.brokerterminal.proto.ValueRef getValue() {
      if (valueBuilder_ == null) {
        return value_ == null ? com.example.brokerterminal.proto.ValueRef.getDefaultInstance() : value_;
      } else {
        return valueBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Описание значения поля
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.ValueRef value = 2;</code>
     */
    public Builder setValue(com.example.brokerterminal.proto.ValueRef value) {
      if (valueBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        value_ = value;
      } else {
        valueBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Описание значения поля
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.ValueRef value = 2;</code>
     */
    public Builder setValue(
        com.example.brokerterminal.proto.ValueRef.Builder builderForValue) {
      if (valueBuilder_ == null) {
        value_ = builderForValue.build();
      } else {
        valueBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Описание значения поля
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.ValueRef value = 2;</code>
     */
    public Builder mergeValue(com.example.brokerterminal.proto.ValueRef value) {
      if (valueBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          value_ != null &&
          value_ != com.example.brokerterminal.proto.ValueRef.getDefaultInstance()) {
          getValueBuilder().mergeFrom(value);
        } else {
          value_ = value;
        }
      } else {
        valueBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Описание значения поля
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.ValueRef value = 2;</code>
     */
    public Builder clearValue() {
      bitField0_ = (bitField0_ & ~0x00000002);
      value_ = null;
      if (valueBuilder_ != null) {
        valueBuilder_.dispose();
        valueBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Описание значения поля
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.ValueRef value = 2;</code>
     */
    public com.example.brokerterminal.proto.ValueRef.Builder getValueBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getValueFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Описание значения поля
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.ValueRef value = 2;</code>
     */
    public com.example.brokerterminal.proto.ValueRefOrBuilder getValueOrBuilder() {
      if (valueBuilder_ != null) {
        return valueBuilder_.getMessageOrBuilder();
      } else {
        return value_ == null ?
            com.example.brokerterminal.proto.ValueRef.getDefaultInstance() : value_;
      }
    }
    /**
     * <pre>
     * Описание значения поля
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.ValueRef value = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.brokerterminal.proto.ValueRef, com.example.brokerterminal.proto.ValueRef.Builder, com.example.brokerterminal.proto.ValueRefOrBuilder> 
        getValueFieldBuilder() {
      if (valueBuilder_ == null) {
        valueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.brokerterminal.proto.ValueRef, com.example.brokerterminal.proto.ValueRef.Builder, com.example.brokerterminal.proto.ValueRefOrBuilder>(
                getValue(),
                getParentForChildren(),
                isClean());
        value_ = null;
      }
      return valueBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.brokerterminal.proto.DataFieldValue)
  }

  // @@protoc_insertion_point(class_scope:com.example.brokerterminal.proto.DataFieldValue)
  private static final com.example.brokerterminal.proto.DataFieldValue DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.brokerterminal.proto.DataFieldValue();
  }

  public static com.example.brokerterminal.proto.DataFieldValue getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DataFieldValue>
      PARSER = new com.google.protobuf.AbstractParser<DataFieldValue>() {
    @java.lang.Override
    public DataFieldValue parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DataFieldValue> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DataFieldValue> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.brokerterminal.proto.DataFieldValue getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

