// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataFieldValue.proto

package com.example.brokerterminal.proto;

public interface DataFieldValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.brokerterminal.proto.DataFieldValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Идентификатор поля для которого устанавливается значение
   * </pre>
   *
   * <code>string alias = 1;</code>
   * @return The alias.
   */
  java.lang.String getAlias();
  /**
   * <pre>
   * Идентификатор поля для которого устанавливается значение
   * </pre>
   *
   * <code>string alias = 1;</code>
   * @return The bytes for alias.
   */
  com.google.protobuf.ByteString
      getAliasBytes();

  /**
   * <pre>
   * Описание значения поля
   * </pre>
   *
   * <code>.com.example.brokerterminal.proto.ValueRef value = 2;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <pre>
   * Описание значения поля
   * </pre>
   *
   * <code>.com.example.brokerterminal.proto.ValueRef value = 2;</code>
   * @return The value.
   */
  com.example.brokerterminal.proto.ValueRef getValue();
  /**
   * <pre>
   * Описание значения поля
   * </pre>
   *
   * <code>.com.example.brokerterminal.proto.ValueRef value = 2;</code>
   */
  com.example.brokerterminal.proto.ValueRefOrBuilder getValueOrBuilder();
}
