// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataRow.proto

package com.example.brokerterminal.proto;

public interface DataRowOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.brokerterminal.proto.DataRow)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Идентификатор записи
   * </pre>
   *
   * <code>string rowIdent = 1;</code>
   * @return The rowIdent.
   */
  java.lang.String getRowIdent();
  /**
   * <pre>
   * Идентификатор записи
   * </pre>
   *
   * <code>string rowIdent = 1;</code>
   * @return The bytes for rowIdent.
   */
  com.google.protobuf.ByteString
      getRowIdentBytes();

  /**
   * <pre>
   * Инкрементальное удаление записи (Удаление записи при инкрементальной передаче данных)
   * </pre>
   *
   * <code>bool incrementDelete = 2;</code>
   * @return The incrementDelete.
   */
  boolean getIncrementDelete();

  /**
   * <pre>
   * Описание поля с установкой значения поля
   * </pre>
   *
   * <code>repeated .com.example.brokerterminal.proto.DataFieldValue values = 3;</code>
   */
  java.util.List<com.example.brokerterminal.proto.DataFieldValue> 
      getValuesList();
  /**
   * <pre>
   * Описание поля с установкой значения поля
   * </pre>
   *
   * <code>repeated .com.example.brokerterminal.proto.DataFieldValue values = 3;</code>
   */
  com.example.brokerterminal.proto.DataFieldValue getValues(int index);
  /**
   * <pre>
   * Описание поля с установкой значения поля
   * </pre>
   *
   * <code>repeated .com.example.brokerterminal.proto.DataFieldValue values = 3;</code>
   */
  int getValuesCount();
  /**
   * <pre>
   * Описание поля с установкой значения поля
   * </pre>
   *
   * <code>repeated .com.example.brokerterminal.proto.DataFieldValue values = 3;</code>
   */
  java.util.List<? extends com.example.brokerterminal.proto.DataFieldValueOrBuilder> 
      getValuesOrBuilderList();
  /**
   * <pre>
   * Описание поля с установкой значения поля
   * </pre>
   *
   * <code>repeated .com.example.brokerterminal.proto.DataFieldValue values = 3;</code>
   */
  com.example.brokerterminal.proto.DataFieldValueOrBuilder getValuesOrBuilder(
      int index);
}
