// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Event.proto

package com.example.brokerterminal.proto;

public final class EventProto {
  private EventProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_brokerterminal_proto_Event_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_brokerterminal_proto_Event_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Event.proto\022 com.example.brokertermina" +
      "l.proto\032\014Status.proto\"A\n\005Event\0228\n\006status" +
      "\030\001 \001(\0132(.com.example.brokerterminal.prot" +
      "o.StatusB\020B\nEventProtoH\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.example.brokerterminal.proto.StatusProto.getDescriptor(),
        });
    internal_static_com_example_brokerterminal_proto_Event_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_brokerterminal_proto_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_brokerterminal_proto_Event_descriptor,
        new java.lang.String[] { "Status", });
    com.example.brokerterminal.proto.StatusProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
