// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Event.proto

package com.example.brokerterminal.proto;

public interface EventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.brokerterminal.proto.Event)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Статус
   * </pre>
   *
   * <code>.com.example.brokerterminal.proto.Status status = 1;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <pre>
   * Статус
   * </pre>
   *
   * <code>.com.example.brokerterminal.proto.Status status = 1;</code>
   * @return The status.
   */
  com.example.brokerterminal.proto.Status getStatus();
  /**
   * <pre>
   * Статус
   * </pre>
   *
   * <code>.com.example.brokerterminal.proto.Status status = 1;</code>
   */
  com.example.brokerterminal.proto.StatusOrBuilder getStatusOrBuilder();
}
