// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExchangeInfoMessage.proto

package com.example.brokerterminal.proto;

public interface ExchangeInfoMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.example.brokerterminal.proto.ExchangeInfoMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Тело заголовка документа
   * </pre>
   *
   * <code>.com.example.brokerterminal.proto.Header header = 1;</code>
   * @return Whether the header field is set.
   */
  boolean hasHeader();
  /**
   * <pre>
   * Тело заголовка документа
   * </pre>
   *
   * <code>.com.example.brokerterminal.proto.Header header = 1;</code>
   * @return The header.
   */
  com.example.brokerterminal.proto.Header getHeader();
  /**
   * <pre>
   * Тело заголовка документа
   * </pre>
   *
   * <code>.com.example.brokerterminal.proto.Header header = 1;</code>
   */
  com.example.brokerterminal.proto.HeaderOrBuilder getHeaderOrBuilder();

  /**
   * <pre>
   * Тело запроса документа
   * </pre>
   *
   * <code>.com.example.brokerterminal.proto.Request request = 2;</code>
   * @return Whether the request field is set.
   */
  boolean hasRequest();
  /**
   * <pre>
   * Тело запроса документа
   * </pre>
   *
   * <code>.com.example.brokerterminal.proto.Request request = 2;</code>
   * @return The request.
   */
  com.example.brokerterminal.proto.Request getRequest();
  /**
   * <pre>
   * Тело запроса документа
   * </pre>
   *
   * <code>.com.example.brokerterminal.proto.Request request = 2;</code>
   */
  com.example.brokerterminal.proto.RequestOrBuilder getRequestOrBuilder();

  /**
   * <pre>
   * Тело ответа документа
   * </pre>
   *
   * <code>.com.example.brokerterminal.proto.Response response = 3;</code>
   * @return Whether the response field is set.
   */
  boolean hasResponse();
  /**
   * <pre>
   * Тело ответа документа
   * </pre>
   *
   * <code>.com.example.brokerterminal.proto.Response response = 3;</code>
   * @return The response.
   */
  com.example.brokerterminal.proto.Response getResponse();
  /**
   * <pre>
   * Тело ответа документа
   * </pre>
   *
   * <code>.com.example.brokerterminal.proto.Response response = 3;</code>
   */
  com.example.brokerterminal.proto.ResponseOrBuilder getResponseOrBuilder();

  /**
   * <pre>
   * Тело события документа
   * </pre>
   *
   * <code>.com.example.brokerterminal.proto.Event event = 4;</code>
   * @return Whether the event field is set.
   */
  boolean hasEvent();
  /**
   * <pre>
   * Тело события документа
   * </pre>
   *
   * <code>.com.example.brokerterminal.proto.Event event = 4;</code>
   * @return The event.
   */
  com.example.brokerterminal.proto.Event getEvent();
  /**
   * <pre>
   * Тело события документа
   * </pre>
   *
   * <code>.com.example.brokerterminal.proto.Event event = 4;</code>
   */
  com.example.brokerterminal.proto.EventOrBuilder getEventOrBuilder();

  com.example.brokerterminal.proto.ExchangeInfoMessage.BodyCase getBodyCase();
}
