// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExchangeInfoMessage.proto

package com.example.brokerterminal.proto;

public final class ExchangeInfoMessageProto {
  private ExchangeInfoMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_brokerterminal_proto_ExchangeInfoMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_brokerterminal_proto_ExchangeInfoMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031ExchangeInfoMessage.proto\022 com.example" +
      ".brokerterminal.proto\032\014Header.proto\032\rReq" +
      "uest.proto\032\016Response.proto\032\013Event.proto\"" +
      "\217\002\n\023ExchangeInfoMessage\0228\n\006header\030\001 \001(\0132" +
      "(.com.example.brokerterminal.proto.Heade" +
      "r\022<\n\007request\030\002 \001(\0132).com.example.brokert" +
      "erminal.proto.RequestH\000\022>\n\010response\030\003 \001(" +
      "\0132*.com.example.brokerterminal.proto.Res" +
      "ponseH\000\0228\n\005event\030\004 \001(\0132\'.com.example.bro" +
      "kerterminal.proto.EventH\000B\006\n\004bodyB\036B\030Exc" +
      "hangeInfoMessageProtoH\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.example.brokerterminal.proto.HeaderProto.getDescriptor(),
          com.example.brokerterminal.proto.RequestProto.getDescriptor(),
          com.example.brokerterminal.proto.ResponseProto.getDescriptor(),
          com.example.brokerterminal.proto.EventProto.getDescriptor(),
        });
    internal_static_com_example_brokerterminal_proto_ExchangeInfoMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_brokerterminal_proto_ExchangeInfoMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_brokerterminal_proto_ExchangeInfoMessage_descriptor,
        new java.lang.String[] { "Header", "Request", "Response", "Event", "Body", });
    com.example.brokerterminal.proto.HeaderProto.getDescriptor();
    com.example.brokerterminal.proto.RequestProto.getDescriptor();
    com.example.brokerterminal.proto.ResponseProto.getDescriptor();
    com.example.brokerterminal.proto.EventProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
