// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ExchangeInfoMessage.proto

package com.example.brokerterminal.proto;

/**
 * Protobuf type {@code com.example.brokerterminal.proto.ExchangeInfoMessage}
 */
public final class ExchangeInfoMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.brokerterminal.proto.ExchangeInfoMessage)
    ExchangeInfoMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ExchangeInfoMessage.newBuilder() to construct.
  private ExchangeInfoMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExchangeInfoMessage() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ExchangeInfoMessage();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.brokerterminal.proto.ExchangeInfoMessageProto.internal_static_com_example_brokerterminal_proto_ExchangeInfoMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.brokerterminal.proto.ExchangeInfoMessageProto.internal_static_com_example_brokerterminal_proto_ExchangeInfoMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.brokerterminal.proto.ExchangeInfoMessage.class, com.example.brokerterminal.proto.ExchangeInfoMessage.Builder.class);
  }

  private int bodyCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object body_;
  public enum BodyCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    REQUEST(2),
    RESPONSE(3),
    EVENT(4),
    BODY_NOT_SET(0);
    private final int value;
    private BodyCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static BodyCase valueOf(int value) {
      return forNumber(value);
    }

    public static BodyCase forNumber(int value) {
      switch (value) {
        case 2: return REQUEST;
        case 3: return RESPONSE;
        case 4: return EVENT;
        case 0: return BODY_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public BodyCase
  getBodyCase() {
    return BodyCase.forNumber(
        bodyCase_);
  }

  public static final int HEADER_FIELD_NUMBER = 1;
  private com.example.brokerterminal.proto.Header header_;
  /**
   * <pre>
   * Тело заголовка документа
   * </pre>
   *
   * <code>.com.example.brokerterminal.proto.Header header = 1;</code>
   * @return Whether the header field is set.
   */
  @java.lang.Override
  public boolean hasHeader() {
    return header_ != null;
  }
  /**
   * <pre>
   * Тело заголовка документа
   * </pre>
   *
   * <code>.com.example.brokerterminal.proto.Header header = 1;</code>
   * @return The header.
   */
  @java.lang.Override
  public com.example.brokerterminal.proto.Header getHeader() {
    return header_ == null ? com.example.brokerterminal.proto.Header.getDefaultInstance() : header_;
  }
  /**
   * <pre>
   * Тело заголовка документа
   * </pre>
   *
   * <code>.com.example.brokerterminal.proto.Header header = 1;</code>
   */
  @java.lang.Override
  public com.example.brokerterminal.proto.HeaderOrBuilder getHeaderOrBuilder() {
    return header_ == null ? com.example.brokerterminal.proto.Header.getDefaultInstance() : header_;
  }

  public static final int REQUEST_FIELD_NUMBER = 2;
  /**
   * <pre>
   * Тело запроса документа
   * </pre>
   *
   * <code>.com.example.brokerterminal.proto.Request request = 2;</code>
   * @return Whether the request field is set.
   */
  @java.lang.Override
  public boolean hasRequest() {
    return bodyCase_ == 2;
  }
  /**
   * <pre>
   * Тело запроса документа
   * </pre>
   *
   * <code>.com.example.brokerterminal.proto.Request request = 2;</code>
   * @return The request.
   */
  @java.lang.Override
  public com.example.brokerterminal.proto.Request getRequest() {
    if (bodyCase_ == 2) {
       return (com.example.brokerterminal.proto.Request) body_;
    }
    return com.example.brokerterminal.proto.Request.getDefaultInstance();
  }
  /**
   * <pre>
   * Тело запроса документа
   * </pre>
   *
   * <code>.com.example.brokerterminal.proto.Request request = 2;</code>
   */
  @java.lang.Override
  public com.example.brokerterminal.proto.RequestOrBuilder getRequestOrBuilder() {
    if (bodyCase_ == 2) {
       return (com.example.brokerterminal.proto.Request) body_;
    }
    return com.example.brokerterminal.proto.Request.getDefaultInstance();
  }

  public static final int RESPONSE_FIELD_NUMBER = 3;
  /**
   * <pre>
   * Тело ответа документа
   * </pre>
   *
   * <code>.com.example.brokerterminal.proto.Response response = 3;</code>
   * @return Whether the response field is set.
   */
  @java.lang.Override
  public boolean hasResponse() {
    return bodyCase_ == 3;
  }
  /**
   * <pre>
   * Тело ответа документа
   * </pre>
   *
   * <code>.com.example.brokerterminal.proto.Response response = 3;</code>
   * @return The response.
   */
  @java.lang.Override
  public com.example.brokerterminal.proto.Response getResponse() {
    if (bodyCase_ == 3) {
       return (com.example.brokerterminal.proto.Response) body_;
    }
    return com.example.brokerterminal.proto.Response.getDefaultInstance();
  }
  /**
   * <pre>
   * Тело ответа документа
   * </pre>
   *
   * <code>.com.example.brokerterminal.proto.Response response = 3;</code>
   */
  @java.lang.Override
  public com.example.brokerterminal.proto.ResponseOrBuilder getResponseOrBuilder() {
    if (bodyCase_ == 3) {
       return (com.example.brokerterminal.proto.Response) body_;
    }
    return com.example.brokerterminal.proto.Response.getDefaultInstance();
  }

  public static final int EVENT_FIELD_NUMBER = 4;
  /**
   * <pre>
   * Тело события документа
   * </pre>
   *
   * <code>.com.example.brokerterminal.proto.Event event = 4;</code>
   * @return Whether the event field is set.
   */
  @java.lang.Override
  public boolean hasEvent() {
    return bodyCase_ == 4;
  }
  /**
   * <pre>
   * Тело события документа
   * </pre>
   *
   * <code>.com.example.brokerterminal.proto.Event event = 4;</code>
   * @return The event.
   */
  @java.lang.Override
  public com.example.brokerterminal.proto.Event getEvent() {
    if (bodyCase_ == 4) {
       return (com.example.brokerterminal.proto.Event) body_;
    }
    return com.example.brokerterminal.proto.Event.getDefaultInstance();
  }
  /**
   * <pre>
   * Тело события документа
   * </pre>
   *
   * <code>.com.example.brokerterminal.proto.Event event = 4;</code>
   */
  @java.lang.Override
  public com.example.brokerterminal.proto.EventOrBuilder getEventOrBuilder() {
    if (bodyCase_ == 4) {
       return (com.example.brokerterminal.proto.Event) body_;
    }
    return com.example.brokerterminal.proto.Event.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (header_ != null) {
      output.writeMessage(1, getHeader());
    }
    if (bodyCase_ == 2) {
      output.writeMessage(2, (com.example.brokerterminal.proto.Request) body_);
    }
    if (bodyCase_ == 3) {
      output.writeMessage(3, (com.example.brokerterminal.proto.Response) body_);
    }
    if (bodyCase_ == 4) {
      output.writeMessage(4, (com.example.brokerterminal.proto.Event) body_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (header_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getHeader());
    }
    if (bodyCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.example.brokerterminal.proto.Request) body_);
    }
    if (bodyCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.example.brokerterminal.proto.Response) body_);
    }
    if (bodyCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (com.example.brokerterminal.proto.Event) body_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.brokerterminal.proto.ExchangeInfoMessage)) {
      return super.equals(obj);
    }
    com.example.brokerterminal.proto.ExchangeInfoMessage other = (com.example.brokerterminal.proto.ExchangeInfoMessage) obj;

    if (hasHeader() != other.hasHeader()) return false;
    if (hasHeader()) {
      if (!getHeader()
          .equals(other.getHeader())) return false;
    }
    if (!getBodyCase().equals(other.getBodyCase())) return false;
    switch (bodyCase_) {
      case 2:
        if (!getRequest()
            .equals(other.getRequest())) return false;
        break;
      case 3:
        if (!getResponse()
            .equals(other.getResponse())) return false;
        break;
      case 4:
        if (!getEvent()
            .equals(other.getEvent())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasHeader()) {
      hash = (37 * hash) + HEADER_FIELD_NUMBER;
      hash = (53 * hash) + getHeader().hashCode();
    }
    switch (bodyCase_) {
      case 2:
        hash = (37 * hash) + REQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getRequest().hashCode();
        break;
      case 3:
        hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getResponse().hashCode();
        break;
      case 4:
        hash = (37 * hash) + EVENT_FIELD_NUMBER;
        hash = (53 * hash) + getEvent().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.brokerterminal.proto.ExchangeInfoMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.brokerterminal.proto.ExchangeInfoMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.brokerterminal.proto.ExchangeInfoMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.brokerterminal.proto.ExchangeInfoMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.brokerterminal.proto.ExchangeInfoMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.brokerterminal.proto.ExchangeInfoMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.brokerterminal.proto.ExchangeInfoMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.brokerterminal.proto.ExchangeInfoMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.brokerterminal.proto.ExchangeInfoMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.brokerterminal.proto.ExchangeInfoMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.brokerterminal.proto.ExchangeInfoMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.brokerterminal.proto.ExchangeInfoMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.brokerterminal.proto.ExchangeInfoMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.brokerterminal.proto.ExchangeInfoMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.brokerterminal.proto.ExchangeInfoMessage)
      com.example.brokerterminal.proto.ExchangeInfoMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.brokerterminal.proto.ExchangeInfoMessageProto.internal_static_com_example_brokerterminal_proto_ExchangeInfoMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.brokerterminal.proto.ExchangeInfoMessageProto.internal_static_com_example_brokerterminal_proto_ExchangeInfoMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.brokerterminal.proto.ExchangeInfoMessage.class, com.example.brokerterminal.proto.ExchangeInfoMessage.Builder.class);
    }

    // Construct using com.example.brokerterminal.proto.ExchangeInfoMessage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      header_ = null;
      if (headerBuilder_ != null) {
        headerBuilder_.dispose();
        headerBuilder_ = null;
      }
      if (requestBuilder_ != null) {
        requestBuilder_.clear();
      }
      if (responseBuilder_ != null) {
        responseBuilder_.clear();
      }
      if (eventBuilder_ != null) {
        eventBuilder_.clear();
      }
      bodyCase_ = 0;
      body_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.brokerterminal.proto.ExchangeInfoMessageProto.internal_static_com_example_brokerterminal_proto_ExchangeInfoMessage_descriptor;
    }

    @java.lang.Override
    public com.example.brokerterminal.proto.ExchangeInfoMessage getDefaultInstanceForType() {
      return com.example.brokerterminal.proto.ExchangeInfoMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.brokerterminal.proto.ExchangeInfoMessage build() {
      com.example.brokerterminal.proto.ExchangeInfoMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.brokerterminal.proto.ExchangeInfoMessage buildPartial() {
      com.example.brokerterminal.proto.ExchangeInfoMessage result = new com.example.brokerterminal.proto.ExchangeInfoMessage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.example.brokerterminal.proto.ExchangeInfoMessage result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.header_ = headerBuilder_ == null
            ? header_
            : headerBuilder_.build();
      }
    }

    private void buildPartialOneofs(com.example.brokerterminal.proto.ExchangeInfoMessage result) {
      result.bodyCase_ = bodyCase_;
      result.body_ = this.body_;
      if (bodyCase_ == 2 &&
          requestBuilder_ != null) {
        result.body_ = requestBuilder_.build();
      }
      if (bodyCase_ == 3 &&
          responseBuilder_ != null) {
        result.body_ = responseBuilder_.build();
      }
      if (bodyCase_ == 4 &&
          eventBuilder_ != null) {
        result.body_ = eventBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.brokerterminal.proto.ExchangeInfoMessage) {
        return mergeFrom((com.example.brokerterminal.proto.ExchangeInfoMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.brokerterminal.proto.ExchangeInfoMessage other) {
      if (other == com.example.brokerterminal.proto.ExchangeInfoMessage.getDefaultInstance()) return this;
      if (other.hasHeader()) {
        mergeHeader(other.getHeader());
      }
      switch (other.getBodyCase()) {
        case REQUEST: {
          mergeRequest(other.getRequest());
          break;
        }
        case RESPONSE: {
          mergeResponse(other.getResponse());
          break;
        }
        case EVENT: {
          mergeEvent(other.getEvent());
          break;
        }
        case BODY_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getHeaderFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getRequestFieldBuilder().getBuilder(),
                  extensionRegistry);
              bodyCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getResponseFieldBuilder().getBuilder(),
                  extensionRegistry);
              bodyCase_ = 3;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getEventFieldBuilder().getBuilder(),
                  extensionRegistry);
              bodyCase_ = 4;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bodyCase_ = 0;
    private java.lang.Object body_;
    public BodyCase
        getBodyCase() {
      return BodyCase.forNumber(
          bodyCase_);
    }

    public Builder clearBody() {
      bodyCase_ = 0;
      body_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.example.brokerterminal.proto.Header header_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.brokerterminal.proto.Header, com.example.brokerterminal.proto.Header.Builder, com.example.brokerterminal.proto.HeaderOrBuilder> headerBuilder_;
    /**
     * <pre>
     * Тело заголовка документа
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.Header header = 1;</code>
     * @return Whether the header field is set.
     */
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Тело заголовка документа
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.Header header = 1;</code>
     * @return The header.
     */
    public com.example.brokerterminal.proto.Header getHeader() {
      if (headerBuilder_ == null) {
        return header_ == null ? com.example.brokerterminal.proto.Header.getDefaultInstance() : header_;
      } else {
        return headerBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Тело заголовка документа
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.Header header = 1;</code>
     */
    public Builder setHeader(com.example.brokerterminal.proto.Header value) {
      if (headerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        header_ = value;
      } else {
        headerBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Тело заголовка документа
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.Header header = 1;</code>
     */
    public Builder setHeader(
        com.example.brokerterminal.proto.Header.Builder builderForValue) {
      if (headerBuilder_ == null) {
        header_ = builderForValue.build();
      } else {
        headerBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Тело заголовка документа
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.Header header = 1;</code>
     */
    public Builder mergeHeader(com.example.brokerterminal.proto.Header value) {
      if (headerBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          header_ != null &&
          header_ != com.example.brokerterminal.proto.Header.getDefaultInstance()) {
          getHeaderBuilder().mergeFrom(value);
        } else {
          header_ = value;
        }
      } else {
        headerBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Тело заголовка документа
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.Header header = 1;</code>
     */
    public Builder clearHeader() {
      bitField0_ = (bitField0_ & ~0x00000001);
      header_ = null;
      if (headerBuilder_ != null) {
        headerBuilder_.dispose();
        headerBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Тело заголовка документа
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.Header header = 1;</code>
     */
    public com.example.brokerterminal.proto.Header.Builder getHeaderBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getHeaderFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Тело заголовка документа
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.Header header = 1;</code>
     */
    public com.example.brokerterminal.proto.HeaderOrBuilder getHeaderOrBuilder() {
      if (headerBuilder_ != null) {
        return headerBuilder_.getMessageOrBuilder();
      } else {
        return header_ == null ?
            com.example.brokerterminal.proto.Header.getDefaultInstance() : header_;
      }
    }
    /**
     * <pre>
     * Тело заголовка документа
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.Header header = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.brokerterminal.proto.Header, com.example.brokerterminal.proto.Header.Builder, com.example.brokerterminal.proto.HeaderOrBuilder> 
        getHeaderFieldBuilder() {
      if (headerBuilder_ == null) {
        headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.brokerterminal.proto.Header, com.example.brokerterminal.proto.Header.Builder, com.example.brokerterminal.proto.HeaderOrBuilder>(
                getHeader(),
                getParentForChildren(),
                isClean());
        header_ = null;
      }
      return headerBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.brokerterminal.proto.Request, com.example.brokerterminal.proto.Request.Builder, com.example.brokerterminal.proto.RequestOrBuilder> requestBuilder_;
    /**
     * <pre>
     * Тело запроса документа
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.Request request = 2;</code>
     * @return Whether the request field is set.
     */
    @java.lang.Override
    public boolean hasRequest() {
      return bodyCase_ == 2;
    }
    /**
     * <pre>
     * Тело запроса документа
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.Request request = 2;</code>
     * @return The request.
     */
    @java.lang.Override
    public com.example.brokerterminal.proto.Request getRequest() {
      if (requestBuilder_ == null) {
        if (bodyCase_ == 2) {
          return (com.example.brokerterminal.proto.Request) body_;
        }
        return com.example.brokerterminal.proto.Request.getDefaultInstance();
      } else {
        if (bodyCase_ == 2) {
          return requestBuilder_.getMessage();
        }
        return com.example.brokerterminal.proto.Request.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Тело запроса документа
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.Request request = 2;</code>
     */
    public Builder setRequest(com.example.brokerterminal.proto.Request value) {
      if (requestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        body_ = value;
        onChanged();
      } else {
        requestBuilder_.setMessage(value);
      }
      bodyCase_ = 2;
      return this;
    }
    /**
     * <pre>
     * Тело запроса документа
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.Request request = 2;</code>
     */
    public Builder setRequest(
        com.example.brokerterminal.proto.Request.Builder builderForValue) {
      if (requestBuilder_ == null) {
        body_ = builderForValue.build();
        onChanged();
      } else {
        requestBuilder_.setMessage(builderForValue.build());
      }
      bodyCase_ = 2;
      return this;
    }
    /**
     * <pre>
     * Тело запроса документа
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.Request request = 2;</code>
     */
    public Builder mergeRequest(com.example.brokerterminal.proto.Request value) {
      if (requestBuilder_ == null) {
        if (bodyCase_ == 2 &&
            body_ != com.example.brokerterminal.proto.Request.getDefaultInstance()) {
          body_ = com.example.brokerterminal.proto.Request.newBuilder((com.example.brokerterminal.proto.Request) body_)
              .mergeFrom(value).buildPartial();
        } else {
          body_ = value;
        }
        onChanged();
      } else {
        if (bodyCase_ == 2) {
          requestBuilder_.mergeFrom(value);
        } else {
          requestBuilder_.setMessage(value);
        }
      }
      bodyCase_ = 2;
      return this;
    }
    /**
     * <pre>
     * Тело запроса документа
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.Request request = 2;</code>
     */
    public Builder clearRequest() {
      if (requestBuilder_ == null) {
        if (bodyCase_ == 2) {
          bodyCase_ = 0;
          body_ = null;
          onChanged();
        }
      } else {
        if (bodyCase_ == 2) {
          bodyCase_ = 0;
          body_ = null;
        }
        requestBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Тело запроса документа
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.Request request = 2;</code>
     */
    public com.example.brokerterminal.proto.Request.Builder getRequestBuilder() {
      return getRequestFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Тело запроса документа
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.Request request = 2;</code>
     */
    @java.lang.Override
    public com.example.brokerterminal.proto.RequestOrBuilder getRequestOrBuilder() {
      if ((bodyCase_ == 2) && (requestBuilder_ != null)) {
        return requestBuilder_.getMessageOrBuilder();
      } else {
        if (bodyCase_ == 2) {
          return (com.example.brokerterminal.proto.Request) body_;
        }
        return com.example.brokerterminal.proto.Request.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Тело запроса документа
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.Request request = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.brokerterminal.proto.Request, com.example.brokerterminal.proto.Request.Builder, com.example.brokerterminal.proto.RequestOrBuilder> 
        getRequestFieldBuilder() {
      if (requestBuilder_ == null) {
        if (!(bodyCase_ == 2)) {
          body_ = com.example.brokerterminal.proto.Request.getDefaultInstance();
        }
        requestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.brokerterminal.proto.Request, com.example.brokerterminal.proto.Request.Builder, com.example.brokerterminal.proto.RequestOrBuilder>(
                (com.example.brokerterminal.proto.Request) body_,
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      bodyCase_ = 2;
      onChanged();
      return requestBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.brokerterminal.proto.Response, com.example.brokerterminal.proto.Response.Builder, com.example.brokerterminal.proto.ResponseOrBuilder> responseBuilder_;
    /**
     * <pre>
     * Тело ответа документа
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.Response response = 3;</code>
     * @return Whether the response field is set.
     */
    @java.lang.Override
    public boolean hasResponse() {
      return bodyCase_ == 3;
    }
    /**
     * <pre>
     * Тело ответа документа
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.Response response = 3;</code>
     * @return The response.
     */
    @java.lang.Override
    public com.example.brokerterminal.proto.Response getResponse() {
      if (responseBuilder_ == null) {
        if (bodyCase_ == 3) {
          return (com.example.brokerterminal.proto.Response) body_;
        }
        return com.example.brokerterminal.proto.Response.getDefaultInstance();
      } else {
        if (bodyCase_ == 3) {
          return responseBuilder_.getMessage();
        }
        return com.example.brokerterminal.proto.Response.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Тело ответа документа
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.Response response = 3;</code>
     */
    public Builder setResponse(com.example.brokerterminal.proto.Response value) {
      if (responseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        body_ = value;
        onChanged();
      } else {
        responseBuilder_.setMessage(value);
      }
      bodyCase_ = 3;
      return this;
    }
    /**
     * <pre>
     * Тело ответа документа
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.Response response = 3;</code>
     */
    public Builder setResponse(
        com.example.brokerterminal.proto.Response.Builder builderForValue) {
      if (responseBuilder_ == null) {
        body_ = builderForValue.build();
        onChanged();
      } else {
        responseBuilder_.setMessage(builderForValue.build());
      }
      bodyCase_ = 3;
      return this;
    }
    /**
     * <pre>
     * Тело ответа документа
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.Response response = 3;</code>
     */
    public Builder mergeResponse(com.example.brokerterminal.proto.Response value) {
      if (responseBuilder_ == null) {
        if (bodyCase_ == 3 &&
            body_ != com.example.brokerterminal.proto.Response.getDefaultInstance()) {
          body_ = com.example.brokerterminal.proto.Response.newBuilder((com.example.brokerterminal.proto.Response) body_)
              .mergeFrom(value).buildPartial();
        } else {
          body_ = value;
        }
        onChanged();
      } else {
        if (bodyCase_ == 3) {
          responseBuilder_.mergeFrom(value);
        } else {
          responseBuilder_.setMessage(value);
        }
      }
      bodyCase_ = 3;
      return this;
    }
    /**
     * <pre>
     * Тело ответа документа
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.Response response = 3;</code>
     */
    public Builder clearResponse() {
      if (responseBuilder_ == null) {
        if (bodyCase_ == 3) {
          bodyCase_ = 0;
          body_ = null;
          onChanged();
        }
      } else {
        if (bodyCase_ == 3) {
          bodyCase_ = 0;
          body_ = null;
        }
        responseBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Тело ответа документа
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.Response response = 3;</code>
     */
    public com.example.brokerterminal.proto.Response.Builder getResponseBuilder() {
      return getResponseFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Тело ответа документа
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.Response response = 3;</code>
     */
    @java.lang.Override
    public com.example.brokerterminal.proto.ResponseOrBuilder getResponseOrBuilder() {
      if ((bodyCase_ == 3) && (responseBuilder_ != null)) {
        return responseBuilder_.getMessageOrBuilder();
      } else {
        if (bodyCase_ == 3) {
          return (com.example.brokerterminal.proto.Response) body_;
        }
        return com.example.brokerterminal.proto.Response.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Тело ответа документа
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.Response response = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.brokerterminal.proto.Response, com.example.brokerterminal.proto.Response.Builder, com.example.brokerterminal.proto.ResponseOrBuilder> 
        getResponseFieldBuilder() {
      if (responseBuilder_ == null) {
        if (!(bodyCase_ == 3)) {
          body_ = com.example.brokerterminal.proto.Response.getDefaultInstance();
        }
        responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.brokerterminal.proto.Response, com.example.brokerterminal.proto.Response.Builder, com.example.brokerterminal.proto.ResponseOrBuilder>(
                (com.example.brokerterminal.proto.Response) body_,
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      bodyCase_ = 3;
      onChanged();
      return responseBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.brokerterminal.proto.Event, com.example.brokerterminal.proto.Event.Builder, com.example.brokerterminal.proto.EventOrBuilder> eventBuilder_;
    /**
     * <pre>
     * Тело события документа
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.Event event = 4;</code>
     * @return Whether the event field is set.
     */
    @java.lang.Override
    public boolean hasEvent() {
      return bodyCase_ == 4;
    }
    /**
     * <pre>
     * Тело события документа
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.Event event = 4;</code>
     * @return The event.
     */
    @java.lang.Override
    public com.example.brokerterminal.proto.Event getEvent() {
      if (eventBuilder_ == null) {
        if (bodyCase_ == 4) {
          return (com.example.brokerterminal.proto.Event) body_;
        }
        return com.example.brokerterminal.proto.Event.getDefaultInstance();
      } else {
        if (bodyCase_ == 4) {
          return eventBuilder_.getMessage();
        }
        return com.example.brokerterminal.proto.Event.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Тело события документа
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.Event event = 4;</code>
     */
    public Builder setEvent(com.example.brokerterminal.proto.Event value) {
      if (eventBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        body_ = value;
        onChanged();
      } else {
        eventBuilder_.setMessage(value);
      }
      bodyCase_ = 4;
      return this;
    }
    /**
     * <pre>
     * Тело события документа
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.Event event = 4;</code>
     */
    public Builder setEvent(
        com.example.brokerterminal.proto.Event.Builder builderForValue) {
      if (eventBuilder_ == null) {
        body_ = builderForValue.build();
        onChanged();
      } else {
        eventBuilder_.setMessage(builderForValue.build());
      }
      bodyCase_ = 4;
      return this;
    }
    /**
     * <pre>
     * Тело события документа
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.Event event = 4;</code>
     */
    public Builder mergeEvent(com.example.brokerterminal.proto.Event value) {
      if (eventBuilder_ == null) {
        if (bodyCase_ == 4 &&
            body_ != com.example.brokerterminal.proto.Event.getDefaultInstance()) {
          body_ = com.example.brokerterminal.proto.Event.newBuilder((com.example.brokerterminal.proto.Event) body_)
              .mergeFrom(value).buildPartial();
        } else {
          body_ = value;
        }
        onChanged();
      } else {
        if (bodyCase_ == 4) {
          eventBuilder_.mergeFrom(value);
        } else {
          eventBuilder_.setMessage(value);
        }
      }
      bodyCase_ = 4;
      return this;
    }
    /**
     * <pre>
     * Тело события документа
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.Event event = 4;</code>
     */
    public Builder clearEvent() {
      if (eventBuilder_ == null) {
        if (bodyCase_ == 4) {
          bodyCase_ = 0;
          body_ = null;
          onChanged();
        }
      } else {
        if (bodyCase_ == 4) {
          bodyCase_ = 0;
          body_ = null;
        }
        eventBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Тело события документа
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.Event event = 4;</code>
     */
    public com.example.brokerterminal.proto.Event.Builder getEventBuilder() {
      return getEventFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Тело события документа
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.Event event = 4;</code>
     */
    @java.lang.Override
    public com.example.brokerterminal.proto.EventOrBuilder getEventOrBuilder() {
      if ((bodyCase_ == 4) && (eventBuilder_ != null)) {
        return eventBuilder_.getMessageOrBuilder();
      } else {
        if (bodyCase_ == 4) {
          return (com.example.brokerterminal.proto.Event) body_;
        }
        return com.example.brokerterminal.proto.Event.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * Тело события документа
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.Event event = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.brokerterminal.proto.Event, com.example.brokerterminal.proto.Event.Builder, com.example.brokerterminal.proto.EventOrBuilder> 
        getEventFieldBuilder() {
      if (eventBuilder_ == null) {
        if (!(bodyCase_ == 4)) {
          body_ = com.example.brokerterminal.proto.Event.getDefaultInstance();
        }
        eventBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.brokerterminal.proto.Event, com.example.brokerterminal.proto.Event.Builder, com.example.brokerterminal.proto.EventOrBuilder>(
                (com.example.brokerterminal.proto.Event) body_,
                getParentForChildren(),
                isClean());
        body_ = null;
      }
      bodyCase_ = 4;
      onChanged();
      return eventBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.brokerterminal.proto.ExchangeInfoMessage)
  }

  // @@protoc_insertion_point(class_scope:com.example.brokerterminal.proto.ExchangeInfoMessage)
  private static final com.example.brokerterminal.proto.ExchangeInfoMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.brokerterminal.proto.ExchangeInfoMessage();
  }

  public static com.example.brokerterminal.proto.ExchangeInfoMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExchangeInfoMessage>
      PARSER = new com.google.protobuf.AbstractParser<ExchangeInfoMessage>() {
    @java.lang.Override
    public ExchangeInfoMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ExchangeInfoMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ExchangeInfoMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.brokerterminal.proto.ExchangeInfoMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

