// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Parameter.proto

package com.example.brokerterminal.proto;

public final class ParameterProto {
  private ParameterProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_brokerterminal_proto_Parameter_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_brokerterminal_proto_Parameter_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017Parameter.proto\022 com.example.brokerter" +
      "minal.proto\032\016ValueRef.proto\"\242\001\n\tParamete" +
      "r\022\r\n\005alias\030\001 \001(\t\022\024\n\007caption\030\002 \001(\tH\000\210\001\001\022\021" +
      "\n\004hint\030\003 \001(\tH\001\210\001\001\022>\n\005value\030\004 \001(\0132*.com.e" +
      "xample.brokerterminal.proto.ValueRefH\002\210\001" +
      "\001B\n\n\010_captionB\007\n\005_hintB\010\n\006_valueB\024B\016Para" +
      "meterProtoH\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.example.brokerterminal.proto.ValueRefProto.getDescriptor(),
        });
    internal_static_com_example_brokerterminal_proto_Parameter_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_brokerterminal_proto_Parameter_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_brokerterminal_proto_Parameter_descriptor,
        new java.lang.String[] { "Alias", "Caption", "Hint", "Value", "Caption", "Hint", "Value", });
    com.example.brokerterminal.proto.ValueRefProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
