// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Request.proto

package com.example.brokerterminal.proto;

public final class RequestProto {
  private RequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_brokerterminal_proto_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_brokerterminal_proto_Request_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rRequest.proto\022 com.example.brokertermi" +
      "nal.proto\032\022MessageEnums.proto\032\020OwnComman" +
      "d.proto\"\360\001\n\007Request\022>\n\007command\030\001 \001(\0162-.c" +
      "om.example.brokerterminal.proto.CommandT" +
      "ype\022I\n\016commandForExec\030\002 \001(\0132,.com.exampl" +
      "e.brokerterminal.proto.OwnCommandH\000\210\001\001\022G" +
      "\n\021supportedCommands\030\003 \003(\0132,.com.example." +
      "brokerterminal.proto.OwnCommandB\021\n\017_comm" +
      "andForExecB\022B\014RequestProtoH\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.example.brokerterminal.proto.MessageEnumsProto.getDescriptor(),
          com.example.brokerterminal.proto.OwnCommandProto.getDescriptor(),
        });
    internal_static_com_example_brokerterminal_proto_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_brokerterminal_proto_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_brokerterminal_proto_Request_descriptor,
        new java.lang.String[] { "Command", "CommandForExec", "SupportedCommands", "CommandForExec", });
    com.example.brokerterminal.proto.MessageEnumsProto.getDescriptor();
    com.example.brokerterminal.proto.OwnCommandProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
