// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Request.proto

package com.example.brokerterminal.proto;

/**
 * Protobuf type {@code com.example.brokerterminal.proto.Request}
 */
public final class Request extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.example.brokerterminal.proto.Request)
    RequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Request.newBuilder() to construct.
  private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Request() {
    command_ = 0;
    supportedCommands_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Request();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.brokerterminal.proto.RequestProto.internal_static_com_example_brokerterminal_proto_Request_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.brokerterminal.proto.RequestProto.internal_static_com_example_brokerterminal_proto_Request_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.brokerterminal.proto.Request.class, com.example.brokerterminal.proto.Request.Builder.class);
  }

  private int bitField0_;
  public static final int COMMAND_FIELD_NUMBER = 1;
  private int command_ = 0;
  /**
   * <pre>
   * Тип команды запроса (ctHandshake - запрос на приветствие, ctExecCommand - запрос на исполнение команды, ctStatus - запрос статуса сервиса.)
   * </pre>
   *
   * <code>.com.example.brokerterminal.proto.CommandType command = 1;</code>
   * @return The enum numeric value on the wire for command.
   */
  @java.lang.Override public int getCommandValue() {
    return command_;
  }
  /**
   * <pre>
   * Тип команды запроса (ctHandshake - запрос на приветствие, ctExecCommand - запрос на исполнение команды, ctStatus - запрос статуса сервиса.)
   * </pre>
   *
   * <code>.com.example.brokerterminal.proto.CommandType command = 1;</code>
   * @return The command.
   */
  @java.lang.Override public com.example.brokerterminal.proto.MessageEnumsProto.CommandType getCommand() {
    com.example.brokerterminal.proto.MessageEnumsProto.CommandType result = com.example.brokerterminal.proto.MessageEnumsProto.CommandType.forNumber(command_);
    return result == null ? com.example.brokerterminal.proto.MessageEnumsProto.CommandType.UNRECOGNIZED : result;
  }

  public static final int COMMANDFOREXEC_FIELD_NUMBER = 2;
  private com.example.brokerterminal.proto.OwnCommand commandForExec_;
  /**
   * <pre>
   * Тип собственной команды сервиса для исполнения.
   * </pre>
   *
   * <code>optional .com.example.brokerterminal.proto.OwnCommand commandForExec = 2;</code>
   * @return Whether the commandForExec field is set.
   */
  @java.lang.Override
  public boolean hasCommandForExec() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Тип собственной команды сервиса для исполнения.
   * </pre>
   *
   * <code>optional .com.example.brokerterminal.proto.OwnCommand commandForExec = 2;</code>
   * @return The commandForExec.
   */
  @java.lang.Override
  public com.example.brokerterminal.proto.OwnCommand getCommandForExec() {
    return commandForExec_ == null ? com.example.brokerterminal.proto.OwnCommand.getDefaultInstance() : commandForExec_;
  }
  /**
   * <pre>
   * Тип собственной команды сервиса для исполнения.
   * </pre>
   *
   * <code>optional .com.example.brokerterminal.proto.OwnCommand commandForExec = 2;</code>
   */
  @java.lang.Override
  public com.example.brokerterminal.proto.OwnCommandOrBuilder getCommandForExecOrBuilder() {
    return commandForExec_ == null ? com.example.brokerterminal.proto.OwnCommand.getDefaultInstance() : commandForExec_;
  }

  public static final int SUPPORTEDCOMMANDS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<com.example.brokerterminal.proto.OwnCommand> supportedCommands_;
  /**
   * <pre>
   * Список собственных команд сервиса
   * </pre>
   *
   * <code>repeated .com.example.brokerterminal.proto.OwnCommand supportedCommands = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.example.brokerterminal.proto.OwnCommand> getSupportedCommandsList() {
    return supportedCommands_;
  }
  /**
   * <pre>
   * Список собственных команд сервиса
   * </pre>
   *
   * <code>repeated .com.example.brokerterminal.proto.OwnCommand supportedCommands = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.example.brokerterminal.proto.OwnCommandOrBuilder> 
      getSupportedCommandsOrBuilderList() {
    return supportedCommands_;
  }
  /**
   * <pre>
   * Список собственных команд сервиса
   * </pre>
   *
   * <code>repeated .com.example.brokerterminal.proto.OwnCommand supportedCommands = 3;</code>
   */
  @java.lang.Override
  public int getSupportedCommandsCount() {
    return supportedCommands_.size();
  }
  /**
   * <pre>
   * Список собственных команд сервиса
   * </pre>
   *
   * <code>repeated .com.example.brokerterminal.proto.OwnCommand supportedCommands = 3;</code>
   */
  @java.lang.Override
  public com.example.brokerterminal.proto.OwnCommand getSupportedCommands(int index) {
    return supportedCommands_.get(index);
  }
  /**
   * <pre>
   * Список собственных команд сервиса
   * </pre>
   *
   * <code>repeated .com.example.brokerterminal.proto.OwnCommand supportedCommands = 3;</code>
   */
  @java.lang.Override
  public com.example.brokerterminal.proto.OwnCommandOrBuilder getSupportedCommandsOrBuilder(
      int index) {
    return supportedCommands_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (command_ != com.example.brokerterminal.proto.MessageEnumsProto.CommandType.ctHandshake.getNumber()) {
      output.writeEnum(1, command_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getCommandForExec());
    }
    for (int i = 0; i < supportedCommands_.size(); i++) {
      output.writeMessage(3, supportedCommands_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (command_ != com.example.brokerterminal.proto.MessageEnumsProto.CommandType.ctHandshake.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, command_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getCommandForExec());
    }
    for (int i = 0; i < supportedCommands_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, supportedCommands_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.brokerterminal.proto.Request)) {
      return super.equals(obj);
    }
    com.example.brokerterminal.proto.Request other = (com.example.brokerterminal.proto.Request) obj;

    if (command_ != other.command_) return false;
    if (hasCommandForExec() != other.hasCommandForExec()) return false;
    if (hasCommandForExec()) {
      if (!getCommandForExec()
          .equals(other.getCommandForExec())) return false;
    }
    if (!getSupportedCommandsList()
        .equals(other.getSupportedCommandsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COMMAND_FIELD_NUMBER;
    hash = (53 * hash) + command_;
    if (hasCommandForExec()) {
      hash = (37 * hash) + COMMANDFOREXEC_FIELD_NUMBER;
      hash = (53 * hash) + getCommandForExec().hashCode();
    }
    if (getSupportedCommandsCount() > 0) {
      hash = (37 * hash) + SUPPORTEDCOMMANDS_FIELD_NUMBER;
      hash = (53 * hash) + getSupportedCommandsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.brokerterminal.proto.Request parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.brokerterminal.proto.Request parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.brokerterminal.proto.Request parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.brokerterminal.proto.Request parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.brokerterminal.proto.Request parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.brokerterminal.proto.Request parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.brokerterminal.proto.Request parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.brokerterminal.proto.Request parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.brokerterminal.proto.Request parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.brokerterminal.proto.Request parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.brokerterminal.proto.Request parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.brokerterminal.proto.Request parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.brokerterminal.proto.Request prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.example.brokerterminal.proto.Request}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.example.brokerterminal.proto.Request)
      com.example.brokerterminal.proto.RequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.brokerterminal.proto.RequestProto.internal_static_com_example_brokerterminal_proto_Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.brokerterminal.proto.RequestProto.internal_static_com_example_brokerterminal_proto_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.brokerterminal.proto.Request.class, com.example.brokerterminal.proto.Request.Builder.class);
    }

    // Construct using com.example.brokerterminal.proto.Request.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCommandForExecFieldBuilder();
        getSupportedCommandsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      command_ = 0;
      commandForExec_ = null;
      if (commandForExecBuilder_ != null) {
        commandForExecBuilder_.dispose();
        commandForExecBuilder_ = null;
      }
      if (supportedCommandsBuilder_ == null) {
        supportedCommands_ = java.util.Collections.emptyList();
      } else {
        supportedCommands_ = null;
        supportedCommandsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.brokerterminal.proto.RequestProto.internal_static_com_example_brokerterminal_proto_Request_descriptor;
    }

    @java.lang.Override
    public com.example.brokerterminal.proto.Request getDefaultInstanceForType() {
      return com.example.brokerterminal.proto.Request.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.brokerterminal.proto.Request build() {
      com.example.brokerterminal.proto.Request result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.brokerterminal.proto.Request buildPartial() {
      com.example.brokerterminal.proto.Request result = new com.example.brokerterminal.proto.Request(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.example.brokerterminal.proto.Request result) {
      if (supportedCommandsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          supportedCommands_ = java.util.Collections.unmodifiableList(supportedCommands_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.supportedCommands_ = supportedCommands_;
      } else {
        result.supportedCommands_ = supportedCommandsBuilder_.build();
      }
    }

    private void buildPartial0(com.example.brokerterminal.proto.Request result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.command_ = command_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.commandForExec_ = commandForExecBuilder_ == null
            ? commandForExec_
            : commandForExecBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.brokerterminal.proto.Request) {
        return mergeFrom((com.example.brokerterminal.proto.Request)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.brokerterminal.proto.Request other) {
      if (other == com.example.brokerterminal.proto.Request.getDefaultInstance()) return this;
      if (other.command_ != 0) {
        setCommandValue(other.getCommandValue());
      }
      if (other.hasCommandForExec()) {
        mergeCommandForExec(other.getCommandForExec());
      }
      if (supportedCommandsBuilder_ == null) {
        if (!other.supportedCommands_.isEmpty()) {
          if (supportedCommands_.isEmpty()) {
            supportedCommands_ = other.supportedCommands_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureSupportedCommandsIsMutable();
            supportedCommands_.addAll(other.supportedCommands_);
          }
          onChanged();
        }
      } else {
        if (!other.supportedCommands_.isEmpty()) {
          if (supportedCommandsBuilder_.isEmpty()) {
            supportedCommandsBuilder_.dispose();
            supportedCommandsBuilder_ = null;
            supportedCommands_ = other.supportedCommands_;
            bitField0_ = (bitField0_ & ~0x00000004);
            supportedCommandsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSupportedCommandsFieldBuilder() : null;
          } else {
            supportedCommandsBuilder_.addAllMessages(other.supportedCommands_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              command_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getCommandForExecFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              com.example.brokerterminal.proto.OwnCommand m =
                  input.readMessage(
                      com.example.brokerterminal.proto.OwnCommand.parser(),
                      extensionRegistry);
              if (supportedCommandsBuilder_ == null) {
                ensureSupportedCommandsIsMutable();
                supportedCommands_.add(m);
              } else {
                supportedCommandsBuilder_.addMessage(m);
              }
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int command_ = 0;
    /**
     * <pre>
     * Тип команды запроса (ctHandshake - запрос на приветствие, ctExecCommand - запрос на исполнение команды, ctStatus - запрос статуса сервиса.)
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.CommandType command = 1;</code>
     * @return The enum numeric value on the wire for command.
     */
    @java.lang.Override public int getCommandValue() {
      return command_;
    }
    /**
     * <pre>
     * Тип команды запроса (ctHandshake - запрос на приветствие, ctExecCommand - запрос на исполнение команды, ctStatus - запрос статуса сервиса.)
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.CommandType command = 1;</code>
     * @param value The enum numeric value on the wire for command to set.
     * @return This builder for chaining.
     */
    public Builder setCommandValue(int value) {
      command_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Тип команды запроса (ctHandshake - запрос на приветствие, ctExecCommand - запрос на исполнение команды, ctStatus - запрос статуса сервиса.)
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.CommandType command = 1;</code>
     * @return The command.
     */
    @java.lang.Override
    public com.example.brokerterminal.proto.MessageEnumsProto.CommandType getCommand() {
      com.example.brokerterminal.proto.MessageEnumsProto.CommandType result = com.example.brokerterminal.proto.MessageEnumsProto.CommandType.forNumber(command_);
      return result == null ? com.example.brokerterminal.proto.MessageEnumsProto.CommandType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Тип команды запроса (ctHandshake - запрос на приветствие, ctExecCommand - запрос на исполнение команды, ctStatus - запрос статуса сервиса.)
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.CommandType command = 1;</code>
     * @param value The command to set.
     * @return This builder for chaining.
     */
    public Builder setCommand(com.example.brokerterminal.proto.MessageEnumsProto.CommandType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      command_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Тип команды запроса (ctHandshake - запрос на приветствие, ctExecCommand - запрос на исполнение команды, ctStatus - запрос статуса сервиса.)
     * </pre>
     *
     * <code>.com.example.brokerterminal.proto.CommandType command = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCommand() {
      bitField0_ = (bitField0_ & ~0x00000001);
      command_ = 0;
      onChanged();
      return this;
    }

    private com.example.brokerterminal.proto.OwnCommand commandForExec_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.brokerterminal.proto.OwnCommand, com.example.brokerterminal.proto.OwnCommand.Builder, com.example.brokerterminal.proto.OwnCommandOrBuilder> commandForExecBuilder_;
    /**
     * <pre>
     * Тип собственной команды сервиса для исполнения.
     * </pre>
     *
     * <code>optional .com.example.brokerterminal.proto.OwnCommand commandForExec = 2;</code>
     * @return Whether the commandForExec field is set.
     */
    public boolean hasCommandForExec() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Тип собственной команды сервиса для исполнения.
     * </pre>
     *
     * <code>optional .com.example.brokerterminal.proto.OwnCommand commandForExec = 2;</code>
     * @return The commandForExec.
     */
    public com.example.brokerterminal.proto.OwnCommand getCommandForExec() {
      if (commandForExecBuilder_ == null) {
        return commandForExec_ == null ? com.example.brokerterminal.proto.OwnCommand.getDefaultInstance() : commandForExec_;
      } else {
        return commandForExecBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Тип собственной команды сервиса для исполнения.
     * </pre>
     *
     * <code>optional .com.example.brokerterminal.proto.OwnCommand commandForExec = 2;</code>
     */
    public Builder setCommandForExec(com.example.brokerterminal.proto.OwnCommand value) {
      if (commandForExecBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        commandForExec_ = value;
      } else {
        commandForExecBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Тип собственной команды сервиса для исполнения.
     * </pre>
     *
     * <code>optional .com.example.brokerterminal.proto.OwnCommand commandForExec = 2;</code>
     */
    public Builder setCommandForExec(
        com.example.brokerterminal.proto.OwnCommand.Builder builderForValue) {
      if (commandForExecBuilder_ == null) {
        commandForExec_ = builderForValue.build();
      } else {
        commandForExecBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Тип собственной команды сервиса для исполнения.
     * </pre>
     *
     * <code>optional .com.example.brokerterminal.proto.OwnCommand commandForExec = 2;</code>
     */
    public Builder mergeCommandForExec(com.example.brokerterminal.proto.OwnCommand value) {
      if (commandForExecBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          commandForExec_ != null &&
          commandForExec_ != com.example.brokerterminal.proto.OwnCommand.getDefaultInstance()) {
          getCommandForExecBuilder().mergeFrom(value);
        } else {
          commandForExec_ = value;
        }
      } else {
        commandForExecBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Тип собственной команды сервиса для исполнения.
     * </pre>
     *
     * <code>optional .com.example.brokerterminal.proto.OwnCommand commandForExec = 2;</code>
     */
    public Builder clearCommandForExec() {
      bitField0_ = (bitField0_ & ~0x00000002);
      commandForExec_ = null;
      if (commandForExecBuilder_ != null) {
        commandForExecBuilder_.dispose();
        commandForExecBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Тип собственной команды сервиса для исполнения.
     * </pre>
     *
     * <code>optional .com.example.brokerterminal.proto.OwnCommand commandForExec = 2;</code>
     */
    public com.example.brokerterminal.proto.OwnCommand.Builder getCommandForExecBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getCommandForExecFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Тип собственной команды сервиса для исполнения.
     * </pre>
     *
     * <code>optional .com.example.brokerterminal.proto.OwnCommand commandForExec = 2;</code>
     */
    public com.example.brokerterminal.proto.OwnCommandOrBuilder getCommandForExecOrBuilder() {
      if (commandForExecBuilder_ != null) {
        return commandForExecBuilder_.getMessageOrBuilder();
      } else {
        return commandForExec_ == null ?
            com.example.brokerterminal.proto.OwnCommand.getDefaultInstance() : commandForExec_;
      }
    }
    /**
     * <pre>
     * Тип собственной команды сервиса для исполнения.
     * </pre>
     *
     * <code>optional .com.example.brokerterminal.proto.OwnCommand commandForExec = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.brokerterminal.proto.OwnCommand, com.example.brokerterminal.proto.OwnCommand.Builder, com.example.brokerterminal.proto.OwnCommandOrBuilder> 
        getCommandForExecFieldBuilder() {
      if (commandForExecBuilder_ == null) {
        commandForExecBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.brokerterminal.proto.OwnCommand, com.example.brokerterminal.proto.OwnCommand.Builder, com.example.brokerterminal.proto.OwnCommandOrBuilder>(
                getCommandForExec(),
                getParentForChildren(),
                isClean());
        commandForExec_ = null;
      }
      return commandForExecBuilder_;
    }

    private java.util.List<com.example.brokerterminal.proto.OwnCommand> supportedCommands_ =
      java.util.Collections.emptyList();
    private void ensureSupportedCommandsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        supportedCommands_ = new java.util.ArrayList<com.example.brokerterminal.proto.OwnCommand>(supportedCommands_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.brokerterminal.proto.OwnCommand, com.example.brokerterminal.proto.OwnCommand.Builder, com.example.brokerterminal.proto.OwnCommandOrBuilder> supportedCommandsBuilder_;

    /**
     * <pre>
     * Список собственных команд сервиса
     * </pre>
     *
     * <code>repeated .com.example.brokerterminal.proto.OwnCommand supportedCommands = 3;</code>
     */
    public java.util.List<com.example.brokerterminal.proto.OwnCommand> getSupportedCommandsList() {
      if (supportedCommandsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(supportedCommands_);
      } else {
        return supportedCommandsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * Список собственных команд сервиса
     * </pre>
     *
     * <code>repeated .com.example.brokerterminal.proto.OwnCommand supportedCommands = 3;</code>
     */
    public int getSupportedCommandsCount() {
      if (supportedCommandsBuilder_ == null) {
        return supportedCommands_.size();
      } else {
        return supportedCommandsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * Список собственных команд сервиса
     * </pre>
     *
     * <code>repeated .com.example.brokerterminal.proto.OwnCommand supportedCommands = 3;</code>
     */
    public com.example.brokerterminal.proto.OwnCommand getSupportedCommands(int index) {
      if (supportedCommandsBuilder_ == null) {
        return supportedCommands_.get(index);
      } else {
        return supportedCommandsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * Список собственных команд сервиса
     * </pre>
     *
     * <code>repeated .com.example.brokerterminal.proto.OwnCommand supportedCommands = 3;</code>
     */
    public Builder setSupportedCommands(
        int index, com.example.brokerterminal.proto.OwnCommand value) {
      if (supportedCommandsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSupportedCommandsIsMutable();
        supportedCommands_.set(index, value);
        onChanged();
      } else {
        supportedCommandsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Список собственных команд сервиса
     * </pre>
     *
     * <code>repeated .com.example.brokerterminal.proto.OwnCommand supportedCommands = 3;</code>
     */
    public Builder setSupportedCommands(
        int index, com.example.brokerterminal.proto.OwnCommand.Builder builderForValue) {
      if (supportedCommandsBuilder_ == null) {
        ensureSupportedCommandsIsMutable();
        supportedCommands_.set(index, builderForValue.build());
        onChanged();
      } else {
        supportedCommandsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Список собственных команд сервиса
     * </pre>
     *
     * <code>repeated .com.example.brokerterminal.proto.OwnCommand supportedCommands = 3;</code>
     */
    public Builder addSupportedCommands(com.example.brokerterminal.proto.OwnCommand value) {
      if (supportedCommandsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSupportedCommandsIsMutable();
        supportedCommands_.add(value);
        onChanged();
      } else {
        supportedCommandsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * Список собственных команд сервиса
     * </pre>
     *
     * <code>repeated .com.example.brokerterminal.proto.OwnCommand supportedCommands = 3;</code>
     */
    public Builder addSupportedCommands(
        int index, com.example.brokerterminal.proto.OwnCommand value) {
      if (supportedCommandsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSupportedCommandsIsMutable();
        supportedCommands_.add(index, value);
        onChanged();
      } else {
        supportedCommandsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * Список собственных команд сервиса
     * </pre>
     *
     * <code>repeated .com.example.brokerterminal.proto.OwnCommand supportedCommands = 3;</code>
     */
    public Builder addSupportedCommands(
        com.example.brokerterminal.proto.OwnCommand.Builder builderForValue) {
      if (supportedCommandsBuilder_ == null) {
        ensureSupportedCommandsIsMutable();
        supportedCommands_.add(builderForValue.build());
        onChanged();
      } else {
        supportedCommandsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Список собственных команд сервиса
     * </pre>
     *
     * <code>repeated .com.example.brokerterminal.proto.OwnCommand supportedCommands = 3;</code>
     */
    public Builder addSupportedCommands(
        int index, com.example.brokerterminal.proto.OwnCommand.Builder builderForValue) {
      if (supportedCommandsBuilder_ == null) {
        ensureSupportedCommandsIsMutable();
        supportedCommands_.add(index, builderForValue.build());
        onChanged();
      } else {
        supportedCommandsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * Список собственных команд сервиса
     * </pre>
     *
     * <code>repeated .com.example.brokerterminal.proto.OwnCommand supportedCommands = 3;</code>
     */
    public Builder addAllSupportedCommands(
        java.lang.Iterable<? extends com.example.brokerterminal.proto.OwnCommand> values) {
      if (supportedCommandsBuilder_ == null) {
        ensureSupportedCommandsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, supportedCommands_);
        onChanged();
      } else {
        supportedCommandsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * Список собственных команд сервиса
     * </pre>
     *
     * <code>repeated .com.example.brokerterminal.proto.OwnCommand supportedCommands = 3;</code>
     */
    public Builder clearSupportedCommands() {
      if (supportedCommandsBuilder_ == null) {
        supportedCommands_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        supportedCommandsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * Список собственных команд сервиса
     * </pre>
     *
     * <code>repeated .com.example.brokerterminal.proto.OwnCommand supportedCommands = 3;</code>
     */
    public Builder removeSupportedCommands(int index) {
      if (supportedCommandsBuilder_ == null) {
        ensureSupportedCommandsIsMutable();
        supportedCommands_.remove(index);
        onChanged();
      } else {
        supportedCommandsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * Список собственных команд сервиса
     * </pre>
     *
     * <code>repeated .com.example.brokerterminal.proto.OwnCommand supportedCommands = 3;</code>
     */
    public com.example.brokerterminal.proto.OwnCommand.Builder getSupportedCommandsBuilder(
        int index) {
      return getSupportedCommandsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * Список собственных команд сервиса
     * </pre>
     *
     * <code>repeated .com.example.brokerterminal.proto.OwnCommand supportedCommands = 3;</code>
     */
    public com.example.brokerterminal.proto.OwnCommandOrBuilder getSupportedCommandsOrBuilder(
        int index) {
      if (supportedCommandsBuilder_ == null) {
        return supportedCommands_.get(index);  } else {
        return supportedCommandsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * Список собственных команд сервиса
     * </pre>
     *
     * <code>repeated .com.example.brokerterminal.proto.OwnCommand supportedCommands = 3;</code>
     */
    public java.util.List<? extends com.example.brokerterminal.proto.OwnCommandOrBuilder> 
         getSupportedCommandsOrBuilderList() {
      if (supportedCommandsBuilder_ != null) {
        return supportedCommandsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(supportedCommands_);
      }
    }
    /**
     * <pre>
     * Список собственных команд сервиса
     * </pre>
     *
     * <code>repeated .com.example.brokerterminal.proto.OwnCommand supportedCommands = 3;</code>
     */
    public com.example.brokerterminal.proto.OwnCommand.Builder addSupportedCommandsBuilder() {
      return getSupportedCommandsFieldBuilder().addBuilder(
          com.example.brokerterminal.proto.OwnCommand.getDefaultInstance());
    }
    /**
     * <pre>
     * Список собственных команд сервиса
     * </pre>
     *
     * <code>repeated .com.example.brokerterminal.proto.OwnCommand supportedCommands = 3;</code>
     */
    public com.example.brokerterminal.proto.OwnCommand.Builder addSupportedCommandsBuilder(
        int index) {
      return getSupportedCommandsFieldBuilder().addBuilder(
          index, com.example.brokerterminal.proto.OwnCommand.getDefaultInstance());
    }
    /**
     * <pre>
     * Список собственных команд сервиса
     * </pre>
     *
     * <code>repeated .com.example.brokerterminal.proto.OwnCommand supportedCommands = 3;</code>
     */
    public java.util.List<com.example.brokerterminal.proto.OwnCommand.Builder> 
         getSupportedCommandsBuilderList() {
      return getSupportedCommandsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.brokerterminal.proto.OwnCommand, com.example.brokerterminal.proto.OwnCommand.Builder, com.example.brokerterminal.proto.OwnCommandOrBuilder> 
        getSupportedCommandsFieldBuilder() {
      if (supportedCommandsBuilder_ == null) {
        supportedCommandsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.example.brokerterminal.proto.OwnCommand, com.example.brokerterminal.proto.OwnCommand.Builder, com.example.brokerterminal.proto.OwnCommandOrBuilder>(
                supportedCommands_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        supportedCommands_ = null;
      }
      return supportedCommandsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.example.brokerterminal.proto.Request)
  }

  // @@protoc_insertion_point(class_scope:com.example.brokerterminal.proto.Request)
  private static final com.example.brokerterminal.proto.Request DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.brokerterminal.proto.Request();
  }

  public static com.example.brokerterminal.proto.Request getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Request>
      PARSER = new com.google.protobuf.AbstractParser<Request>() {
    @java.lang.Override
    public Request parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Request> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Request> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.brokerterminal.proto.Request getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

