// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Response.proto

package com.example.brokerterminal.proto;

public final class ResponseProto {
  private ResponseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_example_brokerterminal_proto_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_example_brokerterminal_proto_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016Response.proto\022 com.example.brokerterm" +
      "inal.proto\032\022MessageEnums.proto\032\014Status.p" +
      "roto\"\374\001\n\010Response\022>\n\007command\030\001 \001(\0162-.com" +
      ".example.brokerterminal.proto.CommandTyp" +
      "e\022@\n\nanswerType\030\002 \001(\0162,.com.example.brok" +
      "erterminal.proto.AnswerType\022\026\n\terrorText" +
      "\030\003 \001(\tH\000\210\001\001\022=\n\006status\030\004 \001(\0132(.com.exampl" +
      "e.brokerterminal.proto.StatusH\001\210\001\001B\014\n\n_e" +
      "rrorTextB\t\n\007_statusB\023B\rResponseProtoH\001P\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.example.brokerterminal.proto.MessageEnumsProto.getDescriptor(),
          com.example.brokerterminal.proto.StatusProto.getDescriptor(),
        });
    internal_static_com_example_brokerterminal_proto_Response_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_example_brokerterminal_proto_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_example_brokerterminal_proto_Response_descriptor,
        new java.lang.String[] { "Command", "AnswerType", "ErrorText", "Status", "ErrorText", "Status", });
    com.example.brokerterminal.proto.MessageEnumsProto.getDescriptor();
    com.example.brokerterminal.proto.StatusProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
